2016/12/15 13:52:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('Demo 404 page')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testK24/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/page&view=buttons_and_icons
---
2016/12/16 01:55:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('Demo 404 page')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testK24/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/page&view=buttons_and_icons
---
2016/12/16 02:59:36 [error] [php] htmlspecialchars() expects parameter 1 to be string, array given (C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php:108)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(163): renderAttributes()
#1 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1450): tag()
#2 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(628): inputField()
#3 C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php(17): textField()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#8 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(140): SiteController->render()
#9 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CViewAction->runWithParams()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\testK24\index.php(13): CWebApplication->run()
REQUEST_URI=/testK24/index.php?r=site/page&view=forms
in C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php (17)
in C:\xampp\htdocs\testK24\index.php (13)
2016/12/16 02:59:48 [error] [php] htmlspecialchars() expects parameter 1 to be string, array given (C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php:108)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(163): renderAttributes()
#1 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1450): tag()
#2 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(628): inputField()
#3 C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php(17): textField()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#8 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(140): SiteController->render()
#9 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CViewAction->runWithParams()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\testK24\index.php(13): CWebApplication->run()
REQUEST_URI=/testK24/index.php?r=site/page&view=forms
in C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php (17)
in C:\xampp\htdocs\testK24\index.php (13)
2016/12/16 03:02:05 [error] [php] htmlspecialchars() expects parameter 1 to be string, array given (C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php:108)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(163): renderAttributes()
#1 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(1450): tag()
#2 C:\xampp\htdocs\yii\framework\web\helpers\CHtml.php(628): inputField()
#3 C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php(17): textField()
#4 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#5 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#8 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(140): SiteController->render()
#9 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CViewAction->runWithParams()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\testK24\index.php(13): CWebApplication->run()
REQUEST_URI=/testK24/index.php?r=site/page&view=forms
in C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php (17)
in C:\xampp\htdocs\testK24\index.php (13)
2016/12/16 04:27:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested view "Demo 404 page" was not found.' in C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php:112
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(123): CViewAction->resolveView('Demo 404 page')
#1 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#2 C:\xampp\htdocs\yii\framework\web\CController.php(308): CAction->runWithParams(Array)
#3 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CViewAction))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CViewAction), Array)
#5 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('page')
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/page')
#7 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#9 {main}
REQUEST_URI=/testK24/index.php?r=site/page&view=Demo+404+page
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/page&view=buttons_and_icons
---
2016/12/16 04:46:32 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.themes" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\base\CModule.php(105): CComponent->__get('themes')
#1 C:\xampp\htdocs\testK24\themes\new\views\site\index.php(2): CModule->__get('themes')
#2 C:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#5 C:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#6 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(32): CController->render('index')
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/testK24/index.php?r=site/index
---
2016/12/16 08:21:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "SiteController/Login".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('SiteController/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testK24/Index.php?r=SiteController/Login
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/index
---
2016/12/16 08:45:01 [error] [php] Undefined variable: model (C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(140): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CViewAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testK24\index.php(13): CWebApplication->run()
REQUEST_URI=/testK24/index.php?r=site/page&view=forms
in C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php (19)
in C:\xampp\htdocs\testK24\index.php (13)
2016/12/16 08:45:05 [error] [php] Undefined variable: model (C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(140): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CViewAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testK24\index.php(13): CWebApplication->run()
REQUEST_URI=/testK24/index.php?r=site/page&view=forms
in C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php (19)
in C:\xampp\htdocs\testK24\index.php (13)
2016/12/16 08:45:12 [error] [php] Undefined variable: model (C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(140): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CViewAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testK24\index.php(13): CWebApplication->run()
REQUEST_URI=/testK24/index.php?r=site/page&view=forms
in C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php (19)
in C:\xampp\htdocs\testK24\index.php (13)
2016/12/16 08:46:36 [error] [php] Undefined variable: model (C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php:19)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(140): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CViewAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testK24\index.php(13): CWebApplication->run()
REQUEST_URI=/testK24/index.php?r=site/page&view=forms
in C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php (19)
in C:\xampp\htdocs\testK24\index.php (13)
2016/12/16 08:46:59 [error] [php] Undefined variable: model (C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php:24)
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\yii\framework\web\actions\CViewAction.php(140): SiteController->render()
#3 C:\xampp\htdocs\yii\framework\web\actions\CAction.php(76): CViewAction->run()
#4 C:\xampp\htdocs\yii\framework\web\CController.php(308): CViewAction->runWithParams()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\testK24\index.php(13): CWebApplication->run()
REQUEST_URI=/testK24/index.php?r=site/page&view=forms
in C:\xampp\htdocs\testK24\themes\new\views\site\pages\forms.php (24)
in C:\xampp\htdocs\testK24\index.php (13)
2016/12/16 08:49:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Member/memberForm".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Member/memberFo...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testK24/index.php?r=Member/memberForm
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/page&view=forms
---
2016/12/16 08:56:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "memberController/View".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('memberControlle...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testK24/Index.php?r=memberController/View
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/index
---
2016/12/20 07:59:03 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'db_testk24'' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testK24/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=gii/default/index
---
2016/12/20 08:26:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login.php".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('login.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testK24/index.php?r=site/login.php
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/login
---
2016/12/20 08:39:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member/user')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testK24/index.php?r=member/user&view=account
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=member
---
2016/12/20 08:40:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "user".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('user')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('user')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('member/user')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testK24/index.php?r=member/user
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=member
---
2016/12/20 08:41:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "SiteController/Login".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('SiteController/...')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testK24/Index.php?r=SiteController/Login
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=member
---
2016/12/20 08:43:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "Login".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Login')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testK24/Index.php?r=Login
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/index
---
2016/12/20 08:44:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "LoginForm".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('LoginForm')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testK24/Index.php?r=LoginForm
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/index
---
2016/12/20 08:50:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login.php".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('login.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testK24/index.php?r=site/login.php
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/login
---
2016/12/20 08:50:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login.php".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('login.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testK24/index.php?r=site/login.php
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/login
---
2016/12/20 08:52:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login.php".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('login.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testK24/index.php?r=site/login.php
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/login
---
2016/12/20 08:56:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "LoginForm".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('LoginForm')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testK24/Index.php?r=LoginForm
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/login
---
2016/12/20 08:57:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "login".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testK24/Index.php?r=login
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=user/create
---
2016/12/20 09:05:07 [error] [exception.CException] exception 'CException' with message 'Property "User.password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(17): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 09:06:18 [error] [exception.CException] exception 'CException' with message 'Property "User.password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(17): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 09:06:34 [error] [exception.CException] exception 'CException' with message 'Property "User.password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(17): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 09:06:43 [error] [exception.CException] exception 'CException' with message 'Property "User.password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(17): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 09:17:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login.php".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('login.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testK24/index.php?r=site/login.php
---
2016/12/20 09:17:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "login.php".' in C:\xampp\htdocs\yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CController.php(270): CController->missingAction('login.php')
#1 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login.php')
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.php')
#3 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/testK24/index.php?r=site/login.php
---
2016/12/20 09:39:29 [error] [exception.CDbException] exception 'CDbException' with message 'Table "user" does not have a column named "username".' in C:\xampp\htdocs\yii\framework\db\schema\CDbCommandBuilder.php:697
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1523): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(20): CActiveRecord->findByAttributes(Array)
#2 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 09:40:15 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.Username" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(20): CComponent->__get('Username')
#1 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 09:41:53 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.Username" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(20): CComponent->__get('Username')
#1 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 09:42:17 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.Password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(23): CComponent->__get('Password')
#1 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 09:42:49 [error] [exception.CException] exception 'CException' with message 'Property "User.password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(23): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 09:44:44 [error] [exception.CException] exception 'CException' with message 'Property "User.password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(23): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/testK24/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/login
---
2016/12/20 09:45:48 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.Password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(23): CComponent->__get('Password')
#1 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/testK24/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/login
---
2016/12/20 09:52:36 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.passord" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(23): CComponent->__get('passord')
#1 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/testK24/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/index.php?r=site/login
---
2016/12/20 09:56:37 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "check".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(227): CComponent->__call('check', Array)
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(26): CActiveRecord->__call('check', Array)
#2 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(26): User->check('admin')
#3 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 10:08:51 [error] [exception.CException] exception 'CException' with message 'User and its behaviors do not have a method or closure named "encrypt".' in C:\xampp\htdocs\yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(227): CComponent->__call('encrypt', Array)
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(25): CActiveRecord->__call('encrypt', Array)
#2 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(25): User->encrypt('admin')
#3 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#4 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#5 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#6 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#7 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 10:10:23 [error] [exception.CException] exception 'CException' with message 'Property "User.password" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(25): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 10:11:08 [error] [exception.CException] exception 'CException' with message 'Property "User.id" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(28): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 10:11:35 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity._id" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\testK24\protected\components\UserIdentity.php(35): CComponent->__get('_id')
#1 C:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(229): UserIdentity->getId()
#2 C:\xampp\htdocs\testK24\protected\models\LoginForm.php(71): CWebUser->login(Object(UserIdentity), 0)
#3 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(94): LoginForm->login()
#4 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#9 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#10 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
2016/12/20 10:16:38 [error] [exception.CException] exception 'CException' with message 'Property "CWebApplication.site" is not defined.' in C:\xampp\htdocs\yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\yii\framework\base\CModule.php(105): CComponent->__get('site')
#1 C:\xampp\htdocs\testK24\protected\controllers\SiteController.php(95): CModule->__get('site')
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\testK24\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/testK24/Index.php?r=site/login
HTTP_REFERER=http://localhost:8080/testK24/Index.php?r=site/login
---
